"""
mRNA Optimization Tool — source package.

Exposes the public API used by main.ipynb and external scripts. Internal
modules (e.g. complexity_analysis, gceh_module) are imported on demand.
"""

from .optimization import genetic_algorithm, FitnessWeights, GeneticAlgorithm
from .pre_optimization import (
    optimize_codons,
    simple_best_codon_optimization,
    percentile_matching_optimization,
    structure_optimized_beam_search,
)
from .local_repair import local_repair
from .hybrid_pipeline import (
    DEFAULT_HYBRID_REPAIR_WINDOW_NT,
    DEFAULT_HYBRID_REPAIR_MAX_SUBS,
    DEFAULT_HYBRID_REPAIR_GC_TOLERANCE,
    DEFAULT_POLISH_POP_SIZE,
    DEFAULT_POLISH_GENERATIONS,
    DEFAULT_POLISH_MUTATION_RATE,
    DEFAULT_POLISH_SEEDS,
    REPEAT_GUARD_POLISH_WEIGHTS,
    DEGENERACY_GUARD_POLISH_WEIGHTS,
    EXTREME_REPEAT_GUARD_POLISH_WEIGHTS,
    DEFAULT_POLISH_WEIGHTS,
    PolishRunResult,
    MultiSeedPolishResult,
    parse_seed_list,
    sequence_quality_metrics,
    is_degeneracy_clean_candidate,
    is_clean_hybrid_candidate,
    is_strict_hybrid_candidate,
    hybrid_candidate_rank,
    multi_seed_ga_polish,
)
from .utils import (
    translate_dna_to_protein,
    back_translate_protein,
    calculate_cai,
    calculate_gc_content,
    calculate_gc3_content,
    load_codon_table,
    list_available_hosts,
    is_eukaryote_host,
    get_target_gc,
    get_target_gc3,
    harmonization_correlation,
    compute_profile_deviation,
    compute_profile_correlation,
    calculate_codon_pair_score,
    calculate_tai,
    tai_available_for,
    codon_pair_available_for,
)

__version__ = "2.0.0"
__all__ = [
    'genetic_algorithm',
    'FitnessWeights',
    'GeneticAlgorithm',
    'optimize_codons',
    'simple_best_codon_optimization',
    'percentile_matching_optimization',
    'structure_optimized_beam_search',
    'local_repair',
    'DEFAULT_HYBRID_REPAIR_WINDOW_NT',
    'DEFAULT_HYBRID_REPAIR_MAX_SUBS',
    'DEFAULT_HYBRID_REPAIR_GC_TOLERANCE',
    'DEFAULT_POLISH_POP_SIZE',
    'DEFAULT_POLISH_GENERATIONS',
    'DEFAULT_POLISH_MUTATION_RATE',
    'DEFAULT_POLISH_SEEDS',
    'REPEAT_GUARD_POLISH_WEIGHTS',
    'DEGENERACY_GUARD_POLISH_WEIGHTS',
    'EXTREME_REPEAT_GUARD_POLISH_WEIGHTS',
    'DEFAULT_POLISH_WEIGHTS',
    'PolishRunResult',
    'MultiSeedPolishResult',
    'parse_seed_list',
    'sequence_quality_metrics',
    'is_degeneracy_clean_candidate',
    'is_clean_hybrid_candidate',
    'is_strict_hybrid_candidate',
    'hybrid_candidate_rank',
    'multi_seed_ga_polish',
    'translate_dna_to_protein',
    'back_translate_protein',
    'calculate_cai',
    'calculate_gc_content',
    'calculate_gc3_content',
    'load_codon_table',
    'list_available_hosts',
    'is_eukaryote_host',
    'get_target_gc',
    'get_target_gc3',
    'harmonization_correlation',
    'compute_profile_deviation',
    'compute_profile_correlation',
    'calculate_codon_pair_score',
    'calculate_tai',
    'tai_available_for',
    'codon_pair_available_for',
]
